import { AspectRatioKey } from './aspect-ratios';
import { BackgroundConfig } from './backgrounds';
import { ImageBorder, ImageShadow } from '@/lib/store';

export interface PresetConfig {
  id: string;
  name: string;
  description: string;
  aspectRatio: AspectRatioKey;
  backgroundConfig: BackgroundConfig;
  borderRadius: number;
  backgroundBorderRadius: number;
  imageOpacity: number;
  imageScale: number;
  imageBorder: ImageBorder;
  imageShadow: ImageShadow;
  backgroundBlur?: number;
  backgroundNoise?: number;
}

export const presets: PresetConfig[] = [
  {
    id: 'landing-showcase-1',
    name: 'Landing Showcase',
    description: 'Mac background with radial gradient overlay',
    aspectRatio: '16_9',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/mac/mac-asset-8',
      opacity: 1,
    },
    borderRadius: 24,
    backgroundBorderRadius: 24,
    imageOpacity: 1,
    imageScale: 90,
    imageBorder: {
      enabled: true,
      width: 3,
      color: '#ffffff',
      type: 'glassy',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 24,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 20,
      offsetX: 0,
      offsetY: 8,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.25)',
    },
    backgroundBlur: 1,
    backgroundNoise: 15,
  },
  {
    id: 'landing-showcase-2',
    name: 'Bold Landing',
    description: 'Vibrant landing with radiant wallpaper',
    aspectRatio: '16_9',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/radiant/radiant4',
      opacity: 1,
    },
    borderRadius: 32,
    backgroundBorderRadius: 32,
    imageOpacity: 1,
    imageScale: 85,
    imageBorder: {
      enabled: true,
      width: 5,
      color: '#ffffff',
      type: 'ruler',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 24,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 25,
      offsetX: 0,
      offsetY: 10,
      spread: 5,
      color: 'rgba(0, 0, 0, 0.3)',
    },
    backgroundBlur: 3,
    backgroundNoise: 20,
  },
  {
    id: 'landing-showcase-3',
    name: 'Clean Landing',
    description: 'Minimal Mac showcase with soft radial gradient',
    aspectRatio: '16_9',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/mac/mac-asset-7',
      opacity: 1,
    },
    borderRadius: 12,
    backgroundBorderRadius: 12,
    imageOpacity: 1,
    imageScale: 88,
    imageBorder: {
      enabled: true,
      width: 10,
      color: '#e5e5e5',
      type: 'focus',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 12,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 30,
      offsetX: 0,
      offsetY: 12,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.1)',
    },
  },
  {
    id: 'landing-showcase-4',
    name: 'Elegant Landing',
    description: 'Sophisticated landing with elegant wallpaper',
    aspectRatio: '16_9',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/assets/asset-11',
      opacity: 1,
    },
    borderRadius: 16,
    backgroundBorderRadius: 16,
    imageOpacity: 0.95,
    imageScale: 92,
    imageBorder: {
      enabled: true,
      width: 3,
      color: '#ffffff',
      type: 'infinite-mirror',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 16,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 40,
      offsetX: 0,
      offsetY: 0,
      spread: 10,
      color: 'rgba(255, 255, 255, 0.15)',
    },
    backgroundBlur: 10,
    backgroundNoise: 18,
  },
  {
    id: 'instagram-story',
    name: 'Instagram Story',
    description: 'Vertical format for stories with radiant wallpaper',
    aspectRatio: '1_1',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/radiant/radiant9',
      opacity: 1,
    },
    borderRadius: 16,
    backgroundBorderRadius: 16,
    imageOpacity: 1,
    imageScale: 100,
    imageBorder: {
      enabled: true,
      width: 4,
      color: '#000000',
      type: 'ruler',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 16,
      inset: false,
    },
    imageShadow: {
      enabled: false,
      blur: 10,
      offsetX: 0,
      offsetY: 4,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.3)',
    },
  },
  {
    id: 'open-graph-social',
    name: 'Open Graph Social',
    description: 'Professional Open Graph image format for social sharing',
    aspectRatio: 'og_image',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/radiant/radiant1',
      opacity: 1,
    },
    borderRadius: 12,
    backgroundBorderRadius: 12,
    imageOpacity: 1,
    imageScale: 88,
    imageBorder: {
      enabled: true,
      width: 3,
      color: '#ffffff',
      type: 'glassy',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 12,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 20,
      offsetX: 0,
      offsetY: 6,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.2)',
    },
    backgroundBlur: 3,
    backgroundNoise: 12,
  },
  {
    id: 'twitter-banner-profile',
    name: 'Twitter Banner',
    description: 'Wide format banner for Twitter/X profile headers',
    aspectRatio: 'twitter_banner',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/mesh/mesh1',
      opacity: 1,
    },
    borderRadius: 0,
    backgroundBorderRadius: 0,
    imageOpacity: 1,
    imageScale: 92,
    imageBorder: {
      enabled: false,
      width: 0,
      color: '#ffffff',
      type: 'glassy',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 0,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 15,
      offsetX: 0,
      offsetY: 4,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.15)',
    },
    backgroundBlur: 3,
    backgroundNoise: 10,
  },
  {
    id: 'instagram-banner-highlight',
    name: 'Instagram Banner',
    description: 'Square format for Instagram highlight covers',
    aspectRatio: 'instagram_banner',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/radiant/radiant3',
      opacity: 1,
    },
    borderRadius: 0,
    backgroundBorderRadius: 0,
    imageOpacity: 1,
    imageScale: 95,
    imageBorder: {
      enabled: false,
      width: 0,
      color: '#ffffff',
      type: 'glassy',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 0,
      inset: false,
    },
    imageShadow: {
      enabled: false,
      blur: 0,
      offsetX: 0,
      offsetY: 0,
      spread: 0,
      color: 'rgba(0, 0, 0, 0)',
    },
    backgroundBlur: 4,
    backgroundNoise: 9,
  },
  {
    id: 'youtube-banner-channel',
    name: 'YouTube Banner',
    description: 'High-resolution banner for YouTube channel art',
    aspectRatio: 'youtube_banner',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/mesh/mesh2',
      opacity: 1,
    },
    borderRadius: 0,
    backgroundBorderRadius: 0,
    imageOpacity: 1,
    imageScale: 90,
    imageBorder: {
      enabled: false,
      width: 0,
      color: '#ffffff',
      type: 'glassy',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 0,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 20,
      offsetX: 0,
      offsetY: 6,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.2)',
    },
    backgroundBlur: 6,
    backgroundNoise: 11,
  },
  {
    id: 'linkedin-banner-profile',
    name: 'LinkedIn Banner',
    description: 'Wide format banner for LinkedIn profile and company pages',
    aspectRatio: 'linkedin_banner',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/radiant/radiant2',
      opacity: 1,
    },
    borderRadius: 0,
    backgroundBorderRadius: 0,
    imageOpacity: 1,
    imageScale: 93,
    imageBorder: {
      enabled: false,
      width: 0,
      color: '#ffffff',
      type: 'glassy',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 0,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 18,
      offsetX: 0,
      offsetY: 5,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.18)',
    },
    backgroundBlur: 6,
    backgroundNoise: 12,
  },
  // New presets with blur and noise effects
  {
    id: 'cinematic-dream',
    name: 'Cinematic Dream',
    description: 'Dreamy cinematic look with heavy blur and grain',
    aspectRatio: '16_9',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/silk/monochrome',
      opacity: 1,
    },
    borderRadius: 20,
    backgroundBorderRadius: 20,
    imageOpacity: 1,
    imageScale: 88,
    imageBorder: {
      enabled: true,
      width: 4,
      color: '#ffffff',
      type: 'glassy',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 20,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 30,
      offsetX: 0,
      offsetY: 12,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.3)',
    },
    backgroundBlur: 5,
    backgroundNoise: 50,
  },
  {
    id: 'vintage-film',
    name: 'Vintage Film',
    description: 'Classic film grain aesthetic with soft focus',
    aspectRatio: '4_5',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/nature/nature1',
      opacity: 1,
    },
    borderRadius: 8,
    backgroundBorderRadius: 8,
    imageOpacity: 0.98,
    imageScale: 92,
    imageBorder: {
      enabled: true,
      width: 2,
      color: '#f5f5f5',
      type: 'solid',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 8,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 25,
      offsetX: 0,
      offsetY: 8,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.2)',
    },
    backgroundBlur: 15,
    backgroundNoise: 40,
  },
  {
    id: 'soft-focus-portrait',
    name: 'Soft Focus Portrait',
    description: 'Elegant portrait with gentle blur and subtle grain',
    aspectRatio: '4_5',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/radiant/radiant5',
      opacity: 1,
    },
    borderRadius: 24,
    backgroundBorderRadius: 24,
    imageOpacity: 1,
    imageScale: 90,
    imageBorder: {
      enabled: true,
      width: 3,
      color: '#ffffff',
      type: 'focus',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 24,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 35,
      offsetX: 0,
      offsetY: 10,
      spread: 5,
      color: 'rgba(0, 0, 0, 0.15)',
    },
    backgroundBlur: 4,
    backgroundNoise: 34,
  },
  {
    id: 'moody-atmosphere',
    name: 'Moody Atmosphere',
    description: 'Dark, atmospheric look with strong blur and heavy grain',
    aspectRatio: '16_9',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/mesh/mesh3',
      opacity: 1,
    },
    borderRadius: 16,
    backgroundBorderRadius: 16,
    imageOpacity: 0.95,
    imageScale: 85,
    imageBorder: {
      enabled: true,
      width: 2,
      color: '#1a1a1a',
      type: 'solid',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 16,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 40,
      offsetX: 0,
      offsetY: 15,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.4)',
    },
    backgroundBlur: 18,
    backgroundNoise: 45,
  },
  {
    id: 'minimal-grain',
    name: 'Minimal Grain',
    description: 'Clean minimal look with subtle texture',
    aspectRatio: '16_9',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/mac/mac-asset-10',
      opacity: 1,
    },
    borderRadius: 12,
    backgroundBorderRadius: 12,
    imageOpacity: 1,
    imageScale: 94,
    imageBorder: {
      enabled: false,
      width: 0,
      color: '#ffffff',
      type: 'glassy',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 12,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 20,
      offsetX: 0,
      offsetY: 6,
      spread: 0,
      color: 'rgba(0, 0, 0, 0.1)',
    },
    backgroundBlur: 3,
    backgroundNoise: 45,
  },
  {
    id: 'artistic-texture',
    name: 'Artistic Texture',
    description: 'Artistic look with medium blur and pronounced grain',
    aspectRatio: '1_1',
    backgroundConfig: {
      type: 'image',
      value: 'backgrounds/backgrounds/radiant/radiant7',
      opacity: 1,
    },
    borderRadius: 20,
    backgroundBorderRadius: 20,
    imageOpacity: 1,
    imageScale: 88,
    imageBorder: {
      enabled: true,
      width: 4,
      color: '#ffffff',
      type: 'infinite-mirror',
      style: 'default',
      top: true,
      right: true,
      bottom: true,
      left: true,
      borderRadius: 20,
      inset: false,
    },
    imageShadow: {
      enabled: true,
      blur: 28,
      offsetX: 0,
      offsetY: 10,
      spread: 3,
      color: 'rgba(0, 0, 0, 0.25)',
    },
    backgroundBlur: 14,
    backgroundNoise: 30,
  },
];

export const getPresetById = (id: string): PresetConfig | undefined => {
  return presets.find((preset) => preset.id === id);
};

